/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.ConnectionDB;
import Clases.Encriptacion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Geydi
 */
public class ConfiguracionUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ConfiguracionUsuario
     */
    public ConnectionDB myConnDB;
    int idUsuario;
    String nombre;
    String apellidos;
    String correoUsuario;
    String telef;
    String ciudad;
    String pais;
    String contrasennaEncriptada;
    String contrasennaDesencriptada;
    String repContrasenna;
    String rolUsuarioLogueado;
    int idRolUsuarioLogueado;
    String rolSelecionadoFormulario;
    
    
    
    public ConfiguracionUsuario(int p_idUsuario, String rolUsuario) { //Constructor usuario rol administrador / gestor
        initComponents();
        this.setTitle("GESTION DE LIBROS - ACTUALIZACION DE DATOS");
        
        idUsuario = p_idUsuario;
        jOptionPane1.setVisible(false);
        
        jt_correoUsuario.setEnabled(false);
        
        myConnDB = new ConnectionDB ("usuario_libreria","Libreria2024","gestion_libros"); //usuario, contraseña, BD
        
        rolUsuarioLogueado = rolUsuario;
        
        try {
            cargarDatosEnFormulario();
        } catch (SQLException ex) {
            Logger.getLogger(ConfiguracionUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(rolUsuario.equals("Administrador")){
        //    jcb_listaRoles.setSelectedIndex(0); //marcar rol cliente por defecto
            jcb_listaRoles.setEnabled(true);
        }
        else if(rolUsuario.equals("Gestor")){
        //    jcb_listaRoles.setSelectedIndex(2); //marcar rol gestor por defecto
            jcb_listaRoles.setEnabled(false);
        }
        else if(rolUsuario.equals("Cliente")){
        //   jcb_listaRoles.setSelectedIndex(1); //marcar rol gestor por defecto
            jcb_listaRoles.setEnabled(false);
        }
        
    }
    
    public void cargarDatosEnFormulario() throws SQLException
    {
        //traer datos de BD del usuario
        
        myConnDB.connect();
        
        ResultSet usuario = myConnDB.query("SELECT * FROM usuarios where idUsuario = '" + idUsuario +"'");
        while(usuario.next())
            {
               
                nombre = usuario.getString("Nombre");
                apellidos = usuario.getString("Apellido");
                correoUsuario = usuario.getString("CorreoElectronico");
                telef = usuario.getString("Telefono");
                ciudad = usuario.getString("Ciudad");
                pais = usuario.getString("Pais");
                contrasennaEncriptada = usuario.getString("contrasenna");
                rolSelecionadoFormulario = String.valueOf(usuario.getInt("Rol"));
                
              
                //cargar datos en el formulario
                jt_nombre.setText(nombre);
                jt_apellidos.setText(apellidos);
                jt_correoUsuario.setText(correoUsuario);
                jt_telef.setText(telef);
                jt_ciudad.setText(ciudad);
                jt_pais.setText(pais);
                
                jcb_listaRoles.setSelectedIndex(usuario.getInt("Rol")-1);
               
                contrasennaDesencriptada = Encriptacion.javaDecode(contrasennaEncriptada);
                
                jp_contrasenna.setText(contrasennaDesencriptada);
                jp_repContrasenna.setText(contrasennaDesencriptada);
            }

         myConnDB.disconnect();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jt_apellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_correoUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt_telef = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt_ciudad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jp_contrasenna = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jp_repContrasenna = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jt_pais = new javax.swing.JTextField();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel9 = new javax.swing.JLabel();
        jcb_listaRoles = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Actualizar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("DATOS DE USUARIO");

        jt_apellidos.setToolTipText("");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("Correo Electrónico / Usuario:");

        jLabel5.setText("Teléfono:");

        jLabel6.setText("Ciudad:");

        jLabel7.setText("País:");

        jLabel8.setText("Contraseña:");

        jLabel10.setText("Repetir Contraseña:");

        jLabel9.setText("Rol:");

        jcb_listaRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cliente", "Gestor" }));
        jcb_listaRoles.setSelectedIndex(1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jp_repContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(113, 113, 113)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jt_apellidos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_correoUsuario)
                                    .addComponent(jt_telef, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_ciudad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_pais, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_listaRoles, 0, 286, Short.MAX_VALUE)
                                    .addComponent(jp_contrasenna))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(jLabel3)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_correoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_telef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jcb_listaRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jp_contrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jp_repContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // actualizar datos en BD
        char [] inputContrasenna = jp_contrasenna.getPassword();
        char [] inputRepContrasenna = jp_repContrasenna.getPassword();
        
        String rolSelecionadoFormulario = jcb_listaRoles.getSelectedItem().toString();
                
        
        switch (rolSelecionadoFormulario) {
            case "Cliente":
                rolSelecionadoFormulario = "2";
                break;
            case "Administrador":
                rolSelecionadoFormulario = "1";
                break;
            case "Gestor":
                rolSelecionadoFormulario = "3";
                break;
            default:
                rolSelecionadoFormulario = "-1";
        }
        
        
        if (rolSelecionadoFormulario.equals("-1") || jt_nombre.getText().hashCode() == 0 || jt_apellidos.getText().hashCode() == 0 || jt_telef.getText().hashCode() == 0 || jt_ciudad.getText().hashCode() == 0 || jt_pais.getText().hashCode() == 0 )
        {
            //jOptionPane1.setVisible(true);
            jOptionPane1.showMessageDialog(null, "Uno o varios campos están vacios!");
        }
        else if(!Arrays.equals(inputContrasenna, inputRepContrasenna))
        {
            //jOptionPane1.setVisible(true); 
            jOptionPane1.showMessageDialog(null, "Las contraseñas no coinciden!");
        }
        else
        {
             try {
                    //conecto con BD
                    myConnDB.connect();

                    String contrasennaEncriptada = Encriptacion.javaEncode(new String(inputContrasenna));

                    //actualiza en BD --- updateQuery() devuelve 1 si modificó algún registro en BD, 0 sino de devuelve o modifica un registro
                    String query =               
                        "UPDATE usuarios SET" +
                        " Nombre = '" + jt_nombre.getText() + "'," +
                        " Apellido = '" + jt_apellidos.getText() + "'," +
                        " Telefono = '" + jt_telef.getText() + "'," +
                        " Ciudad = '" + jt_ciudad.getText() + "'," +
                        " Pais = '" + jt_pais.getText() + "'," +
                        " Rol = '" + rolSelecionadoFormulario + "'," +
                        " contrasenna = '" + contrasennaEncriptada + "'" +    
                        " WHERE idUsuario = " + idUsuario;        
                        

                     int actualizacionUsuario = myConnDB.updateQuery(query);

                    //desconecto con BD
                    myConnDB.disconnect();

                    jOptionPane1.showMessageDialog(null, "Se ha actualizado correctamente el usuario!");
                    this.setVisible(false);
    //                InicioSesion iniSesion = new InicioSesion();
    //                iniSesion.setVisible(true);

                    } catch (SQLException e) {
                       // throw new Exception("");
                    }
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ConfiguracionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ConfiguracionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ConfiguracionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ConfiguracionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ConfiguracionUsuario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcb_listaRoles;
    private javax.swing.JPasswordField jp_contrasenna;
    private javax.swing.JPasswordField jp_repContrasenna;
    private javax.swing.JTextField jt_apellidos;
    private javax.swing.JTextField jt_ciudad;
    private javax.swing.JTextField jt_correoUsuario;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_pais;
    private javax.swing.JTextField jt_telef;
    // End of variables declaration//GEN-END:variables
}
